provider "aws" {
    region = "us-west-1"
}

resource "aws_instance" "demo-server" {
    ami = "ami-055db685a6d9d5646"
    key_name = "vpc"
    instance_type = "t2.micro"
    subnet_id = aws_subnet.demo_subnet.id
     vpc_security_group_ids = [aws_security_group.demo-vpc-sg.id]
}

terraform init
terraform plan
terraform $TERRAFORM_ACTION -auto-approve

if [ $TERRAFORM_ACTION = "delete" ]; then
	exit 0
else
	cd ../Ansible
	ansible-playbook -i /opt/ansible/inventory/aws_ec2.yaml apache.yaml 
fi
